package constdef

const (
	FUNCTION_SRC_DEMO = iota
	FUNCTION_SRC_AUTOSELLER
	FUNCTION_SRC_ENERGYTRADING
	FUNCTION_SRC_GUANGXIBIANMAO
	FUNCTION_SRC_HOUSETRANSFER
	FUNCTION_SRC_RENTPAYMENT
	FUNCTION_SRC_TIANJS
	FUNCTION_SRC_TRANSFER
)

var FunctionSource = map[int]string{
	FUNCTION_SRC_DEMO:           "DEMO_SRC",
	FUNCTION_SRC_AUTOSELLER:     "AUTOSELLER_SRC",
	FUNCTION_SRC_ENERGYTRADING:  "ENERGYTRADING_SRC",
	FUNCTION_SRC_GUANGXIBIANMAO: "GUANGXIBIANMAO_SRC",
	FUNCTION_SRC_HOUSETRANSFER:  "HOUSETRANSFER_SRC",
	FUNCTION_SRC_RENTPAYMENT:    "RENTPAYMENT_SRC",
	FUNCTION_SRC_TIANJS:         "TIANJS_SRC",
	FUNCTION_SRC_TRANSFER:       "TRANSFER_SRC",
}
