// Code generated by protoc-gen-go.
// source: paramProto.proto
// DO NOT EDIT!

/*
Package paramProto is a generated protocol buffer package.

It is generated from these files:
	paramProto.proto

It has these top-level messages:
	ReqParamStruct
	ResParamStruct
*/
package paramProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReqParamStruct struct {
	RequestId  string `protobuf:"bytes,1,opt,name=requestId" json:"requestId,omitempty"`
	FuncName   string `protobuf:"bytes,2,opt,name=funcName" json:"funcName,omitempty"`
	FuncParams string `protobuf:"bytes,3,opt,name=funcParams" json:"funcParams,omitempty"`
}

func (m *ReqParamStruct) Reset()                    { *m = ReqParamStruct{} }
func (m *ReqParamStruct) String() string            { return proto.CompactTextString(m) }
func (*ReqParamStruct) ProtoMessage()               {}
func (*ReqParamStruct) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ReqParamStruct) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *ReqParamStruct) GetFuncName() string {
	if m != nil {
		return m.FuncName
	}
	return ""
}

func (m *ReqParamStruct) GetFuncParams() string {
	if m != nil {
		return m.FuncParams
	}
	return ""
}

type ResParamStruct struct {
	RequestId string `protobuf:"bytes,1,opt,name=requestId" json:"requestId,omitempty"`
	ResResult string `protobuf:"bytes,2,opt,name=resResult" json:"resResult,omitempty"`
}

func (m *ResParamStruct) Reset()                    { *m = ResParamStruct{} }
func (m *ResParamStruct) String() string            { return proto.CompactTextString(m) }
func (*ResParamStruct) ProtoMessage()               {}
func (*ResParamStruct) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResParamStruct) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *ResParamStruct) GetResResult() string {
	if m != nil {
		return m.ResResult
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqParamStruct)(nil), "paramProto.reqParamStruct")
	proto.RegisterType((*ResParamStruct)(nil), "paramProto.resParamStruct")
}

func init() { proto.RegisterFile("paramProto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x48, 0x2c, 0x4a,
	0xcc, 0x0d, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2b, 0x00, 0x91, 0x42, 0x5c, 0x08, 0x11, 0xa5, 0x2c,
	0x2e, 0xbe, 0xa2, 0xd4, 0xc2, 0x00, 0x90, 0x40, 0x70, 0x49, 0x51, 0x69, 0x72, 0x89, 0x90, 0x0c,
	0x17, 0x67, 0x51, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x67, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06,
	0x67, 0x10, 0x42, 0x40, 0x48, 0x8a, 0x8b, 0x23, 0xad, 0x34, 0x2f, 0xd9, 0x2f, 0x31, 0x37, 0x55,
	0x82, 0x09, 0x2c, 0x09, 0xe7, 0x0b, 0xc9, 0x71, 0x71, 0x81, 0xd8, 0x60, 0xc3, 0x8a, 0x25, 0x98,
	0xc1, 0xb2, 0x48, 0x22, 0x4a, 0x3e, 0x20, 0xbb, 0x8a, 0x89, 0xb7, 0x0b, 0x2c, 0x5b, 0x1c, 0x94,
	0x5a, 0x5c, 0x9a, 0x53, 0x02, 0xb5, 0x0c, 0x21, 0x90, 0xc4, 0x06, 0xf6, 0x8c, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xdb, 0x73, 0xc1, 0x42, 0xe0, 0x00, 0x00, 0x00,
}
