// Code generated by protoc-gen-go.
// source: contract.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ContractSignature struct {
	OwnerPubkey   string `protobuf:"bytes,1,opt,name=OwnerPubkey" json:"OwnerPubkey"`
	Signature     string `protobuf:"bytes,2,opt,name=Signature" json:"Signature"`
	SignTimestamp string `protobuf:"bytes,3,opt,name=SignTimestamp" json:"SignTimestamp"`
}

func (m *ContractSignature) Reset()                    { *m = ContractSignature{} }
func (m *ContractSignature) String() string            { return proto.CompactTextString(m) }
func (*ContractSignature) ProtoMessage()               {}
func (*ContractSignature) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *ContractSignature) GetOwnerPubkey() string {
	if m != nil {
		return m.OwnerPubkey
	}
	return ""
}

func (m *ContractSignature) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *ContractSignature) GetSignTimestamp() string {
	if m != nil {
		return m.SignTimestamp
	}
	return ""
}

type ContractAsset struct {
	AssetId     string  `protobuf:"bytes,1,opt,name=AssetId" json:"AssetId"`
	Name        string  `protobuf:"bytes,2,opt,name=Name" json:"Name"`
	Caption     string  `protobuf:"bytes,3,opt,name=Caption" json:"Caption"`
	Description string  `protobuf:"bytes,4,opt,name=Description" json:"Description"`
	Unit        string  `protobuf:"bytes,5,opt,name=Unit" json:"Unit"`
	Amount      float32 `protobuf:"fixed32,6,opt,name=Amount" json:"Amount"`
	MetaData    []byte  `protobuf:"bytes,7,opt,name=MetaData,proto3" json:"MetaData"`
}

func (m *ContractAsset) Reset()                    { *m = ContractAsset{} }
func (m *ContractAsset) String() string            { return proto.CompactTextString(m) }
func (*ContractAsset) ProtoMessage()               {}
func (*ContractAsset) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ContractAsset) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *ContractAsset) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContractAsset) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *ContractAsset) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ContractAsset) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *ContractAsset) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ContractAsset) GetMetaData() []byte {
	if m != nil {
		return m.MetaData
	}
	return nil
}

type ExpressionResult struct {
	Messsage string `protobuf:"bytes,1,opt,name=Messsage" json:"Messsage"`
	Code     string `protobuf:"bytes,2,opt,name=Code" json:"Code"`
}

func (m *ExpressionResult) Reset()                    { *m = ExpressionResult{} }
func (m *ExpressionResult) String() string            { return proto.CompactTextString(m) }
func (*ExpressionResult) ProtoMessage()               {}
func (*ExpressionResult) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ExpressionResult) GetMesssage() string {
	if m != nil {
		return m.Messsage
	}
	return ""
}

func (m *ExpressionResult) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type ComponentsExpression struct {
	Cname            string            `protobuf:"bytes,1,opt,name=Cname" json:"Cname"`
	Ctype            string            `protobuf:"bytes,2,opt,name=Ctype" json:"Ctype"`
	Caption          string            `protobuf:"bytes,3,opt,name=Caption" json:"Caption"`
	Description      string            `protobuf:"bytes,4,opt,name=Description" json:"Description"`
	ExpressionStr    string            `protobuf:"bytes,5,opt,name=ExpressionStr" json:"ExpressionStr"`
	ExpressionResult *ExpressionResult `protobuf:"bytes,6,opt,name=ExpressionResult" json:"ExpressionResult"`
	LogicValue       string            `protobuf:"bytes,7,opt,name=LogicValue" json:"LogicValue"`
}

func (m *ComponentsExpression) Reset()                    { *m = ComponentsExpression{} }
func (m *ComponentsExpression) String() string            { return proto.CompactTextString(m) }
func (*ComponentsExpression) ProtoMessage()               {}
func (*ComponentsExpression) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *ComponentsExpression) GetCname() string {
	if m != nil {
		return m.Cname
	}
	return ""
}

func (m *ComponentsExpression) GetCtype() string {
	if m != nil {
		return m.Ctype
	}
	return ""
}

func (m *ComponentsExpression) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *ComponentsExpression) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ComponentsExpression) GetExpressionStr() string {
	if m != nil {
		return m.ExpressionStr
	}
	return ""
}

func (m *ComponentsExpression) GetExpressionResult() *ExpressionResult {
	if m != nil {
		return m.ExpressionResult
	}
	return nil
}

func (m *ComponentsExpression) GetLogicValue() string {
	if m != nil {
		return m.LogicValue
	}
	return ""
}

type ComponentData struct {
	Cname        string `protobuf:"bytes,1,opt,name=Cname" json:"Cname"`
	Ctype        string `protobuf:"bytes,2,opt,name=Ctype" json:"Ctype"`
	Caption      string `protobuf:"bytes,3,opt,name=Caption" json:"Caption"`
	Description  string `protobuf:"bytes,4,opt,name=Description" json:"Description"`
	ModifyDate   string `protobuf:"bytes,5,opt,name=ModifyDate" json:"ModifyDate"`
	HardConvType string `protobuf:"bytes,6,opt,name=HardConvType" json:"HardConvType"`
	//    map<string,?> Category = 7; // map[string]interface{} Category
	Parent    *ComponentData `protobuf:"bytes,8,opt,name=Parent" json:"Parent"`
	Mandatory bool           `protobuf:"varint,9,opt,name=Mandatory" json:"Mandatory"`
	//    google.protobuf.Any DefaultValue = 10; // interface{} DefaultValue
	Unit string `protobuf:"bytes,11,opt,name=Unit" json:"Unit"`
	//    google.protobuf.Any Value = 12; // interface{} Value
	Options map[string]int32 `protobuf:"bytes,13,rep,name=Options" json:"Options" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	//    repeated google.protobuf.Any DataRange = 14; // []interface{} DataRange
	Format string `protobuf:"bytes,15,opt,name=Format" json:"Format"`
}

func (m *ComponentData) Reset()                    { *m = ComponentData{} }
func (m *ComponentData) String() string            { return proto.CompactTextString(m) }
func (*ComponentData) ProtoMessage()               {}
func (*ComponentData) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *ComponentData) GetCname() string {
	if m != nil {
		return m.Cname
	}
	return ""
}

func (m *ComponentData) GetCtype() string {
	if m != nil {
		return m.Ctype
	}
	return ""
}

func (m *ComponentData) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *ComponentData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ComponentData) GetModifyDate() string {
	if m != nil {
		return m.ModifyDate
	}
	return ""
}

func (m *ComponentData) GetHardConvType() string {
	if m != nil {
		return m.HardConvType
	}
	return ""
}

func (m *ComponentData) GetParent() *ComponentData {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *ComponentData) GetMandatory() bool {
	if m != nil {
		return m.Mandatory
	}
	return false
}

func (m *ComponentData) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *ComponentData) GetOptions() map[string]int32 {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *ComponentData) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

type SelectBranchExpression struct {
	BranchExpressionStr   string `protobuf:"bytes,1,opt,name=BranchExpressionStr" json:"BranchExpressionStr"`
	BranchExpressionValue string `protobuf:"bytes,2,opt,name=BranchExpressionValue" json:"BranchExpressionValue"`
}

func (m *SelectBranchExpression) Reset()                    { *m = SelectBranchExpression{} }
func (m *SelectBranchExpression) String() string            { return proto.CompactTextString(m) }
func (*SelectBranchExpression) ProtoMessage()               {}
func (*SelectBranchExpression) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *SelectBranchExpression) GetBranchExpressionStr() string {
	if m != nil {
		return m.BranchExpressionStr
	}
	return ""
}

func (m *SelectBranchExpression) GetBranchExpressionValue() string {
	if m != nil {
		return m.BranchExpressionValue
	}
	return ""
}

type ContractComponent struct {
	Cname                         string                  `protobuf:"bytes,1,opt,name=Cname" json:"Cname"`
	Ctype                         string                  `protobuf:"bytes,2,opt,name=Ctype" json:"Ctype"`
	Caption                       string                  `protobuf:"bytes,3,opt,name=Caption" json:"Caption"`
	Description                   string                  `protobuf:"bytes,4,opt,name=Description" json:"Description"`
	State                         string                  `protobuf:"bytes,5,opt,name=State" json:"State"`
	PreCondition                  []*ComponentsExpression `protobuf:"bytes,6,rep,name=PreCondition" json:"PreCondition"`
	CompleteCondition             []*ComponentsExpression `protobuf:"bytes,7,rep,name=CompleteCondition" json:"CompleteCondition"`
	DiscardCondition              []*ComponentsExpression `protobuf:"bytes,8,rep,name=DiscardCondition" json:"DiscardCondition"`
	NextTasks                     []string                `protobuf:"bytes,9,rep,name=NextTasks" json:"NextTasks"`
	DataList                      []*ComponentData        `protobuf:"bytes,10,rep,name=DataList" json:"DataList"`
	DataValueSetterExpressionList []*ComponentsExpression `protobuf:"bytes,11,rep,name=DataValueSetterExpressionList" json:"DataValueSetterExpressionList"`
	CandidateList                 *ContractComponent      `protobuf:"bytes,12,opt,name=CandidateList" json:"CandidateList"`
	DecisionResult                *ContractComponent      `protobuf:"bytes,13,opt,name=DecisionResult" json:"DecisionResult"`
	TaskList                      []string                `protobuf:"bytes,14,rep,name=TaskList" json:"TaskList"`
	SupportArguments              []string                `protobuf:"bytes,15,rep,name=SupportArguments" json:"SupportArguments"`
	AgainstArguments              []string                `protobuf:"bytes,16,rep,name=AgainstArguments" json:"AgainstArguments"`
	Support                       int32                   `protobuf:"varint,17,opt,name=Support" json:"Support"`
	Text                          []string                `protobuf:"bytes,18,rep,name=Text" json:"Text"`
	// add date: 2017-05-11 任务执行索引次数 int
	TaskExecuteIdx int32  `protobuf:"varint,19,opt,name=TaskExecuteIdx" json:"TaskExecuteIdx"`
	TaskId         string `protobuf:"bytes,20,opt,name=TaskId" json:"TaskId"`
	// 2017-05-27 17:10:00 add
	SelectBranches []*SelectBranchExpression `protobuf:"bytes,21,rep,name=SelectBranches" json:"SelectBranches"`
}

func (m *ContractComponent) Reset()                    { *m = ContractComponent{} }
func (m *ContractComponent) String() string            { return proto.CompactTextString(m) }
func (*ContractComponent) ProtoMessage()               {}
func (*ContractComponent) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *ContractComponent) GetCname() string {
	if m != nil {
		return m.Cname
	}
	return ""
}

func (m *ContractComponent) GetCtype() string {
	if m != nil {
		return m.Ctype
	}
	return ""
}

func (m *ContractComponent) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *ContractComponent) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ContractComponent) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ContractComponent) GetPreCondition() []*ComponentsExpression {
	if m != nil {
		return m.PreCondition
	}
	return nil
}

func (m *ContractComponent) GetCompleteCondition() []*ComponentsExpression {
	if m != nil {
		return m.CompleteCondition
	}
	return nil
}

func (m *ContractComponent) GetDiscardCondition() []*ComponentsExpression {
	if m != nil {
		return m.DiscardCondition
	}
	return nil
}

func (m *ContractComponent) GetNextTasks() []string {
	if m != nil {
		return m.NextTasks
	}
	return nil
}

func (m *ContractComponent) GetDataList() []*ComponentData {
	if m != nil {
		return m.DataList
	}
	return nil
}

func (m *ContractComponent) GetDataValueSetterExpressionList() []*ComponentsExpression {
	if m != nil {
		return m.DataValueSetterExpressionList
	}
	return nil
}

func (m *ContractComponent) GetCandidateList() *ContractComponent {
	if m != nil {
		return m.CandidateList
	}
	return nil
}

func (m *ContractComponent) GetDecisionResult() *ContractComponent {
	if m != nil {
		return m.DecisionResult
	}
	return nil
}

func (m *ContractComponent) GetTaskList() []string {
	if m != nil {
		return m.TaskList
	}
	return nil
}

func (m *ContractComponent) GetSupportArguments() []string {
	if m != nil {
		return m.SupportArguments
	}
	return nil
}

func (m *ContractComponent) GetAgainstArguments() []string {
	if m != nil {
		return m.AgainstArguments
	}
	return nil
}

func (m *ContractComponent) GetSupport() int32 {
	if m != nil {
		return m.Support
	}
	return 0
}

func (m *ContractComponent) GetText() []string {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *ContractComponent) GetTaskExecuteIdx() int32 {
	if m != nil {
		return m.TaskExecuteIdx
	}
	return 0
}

func (m *ContractComponent) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *ContractComponent) GetSelectBranches() []*SelectBranchExpression {
	if m != nil {
		return m.SelectBranches
	}
	return nil
}

type ContractBody struct {
	ContractId         string               `protobuf:"bytes,1,opt,name=ContractId" json:"ContractId"`
	Cname              string               `protobuf:"bytes,2,opt,name=Cname" json:"Cname"`
	Ctype              string               `protobuf:"bytes,3,opt,name=Ctype" json:"Ctype"`
	Caption            string               `protobuf:"bytes,4,opt,name=Caption" json:"Caption"`
	Description        string               `protobuf:"bytes,5,opt,name=Description" json:"Description"`
	ContractState      string               `protobuf:"bytes,6,opt,name=ContractState" json:"ContractState"`
	Creator            string               `protobuf:"bytes,7,opt,name=Creator" json:"Creator"`
	CreateTime         string               `protobuf:"bytes,8,opt,name=CreateTime" json:"CreateTime"`
	StartTime          string               `protobuf:"bytes,9,opt,name=StartTime" json:"StartTime"`
	EndTime            string               `protobuf:"bytes,10,opt,name=EndTime" json:"EndTime"`
	ContractOwners     []string             `protobuf:"bytes,11,rep,name=ContractOwners" json:"ContractOwners"`
	ContractAssets     []*ContractAsset     `protobuf:"bytes,12,rep,name=ContractAssets" json:"ContractAssets"`
	ContractSignatures []*ContractSignature `protobuf:"bytes,13,rep,name=ContractSignatures" json:"ContractSignatures"`
	ContractComponents []*ContractComponent `protobuf:"bytes,14,rep,name=ContractComponents" json:"ContractComponents"`
	// add date: 2017-05-11 map[string]interface{} 合约属性MetaData
	MetaAttribute []byte `protobuf:"bytes,15,opt,name=MetaAttribute,proto3" json:"MetaAttribute"`
}

func (m *ContractBody) Reset()                    { *m = ContractBody{} }
func (m *ContractBody) String() string            { return proto.CompactTextString(m) }
func (*ContractBody) ProtoMessage()               {}
func (*ContractBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *ContractBody) GetContractId() string {
	if m != nil {
		return m.ContractId
	}
	return ""
}

func (m *ContractBody) GetCname() string {
	if m != nil {
		return m.Cname
	}
	return ""
}

func (m *ContractBody) GetCtype() string {
	if m != nil {
		return m.Ctype
	}
	return ""
}

func (m *ContractBody) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *ContractBody) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ContractBody) GetContractState() string {
	if m != nil {
		return m.ContractState
	}
	return ""
}

func (m *ContractBody) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ContractBody) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *ContractBody) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *ContractBody) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *ContractBody) GetContractOwners() []string {
	if m != nil {
		return m.ContractOwners
	}
	return nil
}

func (m *ContractBody) GetContractAssets() []*ContractAsset {
	if m != nil {
		return m.ContractAssets
	}
	return nil
}

func (m *ContractBody) GetContractSignatures() []*ContractSignature {
	if m != nil {
		return m.ContractSignatures
	}
	return nil
}

func (m *ContractBody) GetContractComponents() []*ContractComponent {
	if m != nil {
		return m.ContractComponents
	}
	return nil
}

func (m *ContractBody) GetMetaAttribute() []byte {
	if m != nil {
		return m.MetaAttribute
	}
	return nil
}

type ContractHead struct {
	MainPubkey string `protobuf:"bytes,1,opt,name=MainPubkey" json:"MainPubkey"`
	Version    int32  `protobuf:"varint,2,opt,name=Version" json:"Version"`
	// 指派处理时间 add 2017-05-27 17:10:0
	AssignTime string `protobuf:"bytes,3,opt,name=AssignTime" json:"AssignTime"`
	// add date: 2017-05-11 合约执行时间戳
	// 操作时间,记录状态改变时间, Timestamp修改而来 2017-05-27 17:10:0
	OperateTime string `protobuf:"bytes,4,opt,name=OperateTime" json:"OperateTime"`
	// add date: 2017-06-01 共识结果,是否共识等
	ConsensusResult int32 `protobuf:"varint,5,opt,name=ConsensusResult" json:"ConsensusResult"`
}

func (m *ContractHead) Reset()                    { *m = ContractHead{} }
func (m *ContractHead) String() string            { return proto.CompactTextString(m) }
func (*ContractHead) ProtoMessage()               {}
func (*ContractHead) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *ContractHead) GetMainPubkey() string {
	if m != nil {
		return m.MainPubkey
	}
	return ""
}

func (m *ContractHead) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ContractHead) GetAssignTime() string {
	if m != nil {
		return m.AssignTime
	}
	return ""
}

func (m *ContractHead) GetOperateTime() string {
	if m != nil {
		return m.OperateTime
	}
	return ""
}

func (m *ContractHead) GetConsensusResult() int32 {
	if m != nil {
		return m.ConsensusResult
	}
	return 0
}

type Contract struct {
	Id           string        `protobuf:"bytes,1,opt,name=id" json:"id"`
	ContractHead *ContractHead `protobuf:"bytes,2,opt,name=ContractHead" json:"ContractHead"`
	ContractBody *ContractBody `protobuf:"bytes,3,opt,name=ContractBody" json:"ContractBody"`
}

func (m *Contract) Reset()                    { *m = Contract{} }
func (m *Contract) String() string            { return proto.CompactTextString(m) }
func (*Contract) ProtoMessage()               {}
func (*Contract) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *Contract) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Contract) GetContractHead() *ContractHead {
	if m != nil {
		return m.ContractHead
	}
	return nil
}

func (m *Contract) GetContractBody() *ContractBody {
	if m != nil {
		return m.ContractBody
	}
	return nil
}

func init() {
	proto.RegisterType((*ContractSignature)(nil), "protos.ContractSignature")
	proto.RegisterType((*ContractAsset)(nil), "protos.ContractAsset")
	proto.RegisterType((*ExpressionResult)(nil), "protos.ExpressionResult")
	proto.RegisterType((*ComponentsExpression)(nil), "protos.ComponentsExpression")
	proto.RegisterType((*ComponentData)(nil), "protos.ComponentData")
	proto.RegisterType((*SelectBranchExpression)(nil), "protos.SelectBranchExpression")
	proto.RegisterType((*ContractComponent)(nil), "protos.ContractComponent")
	proto.RegisterType((*ContractBody)(nil), "protos.ContractBody")
	proto.RegisterType((*ContractHead)(nil), "protos.ContractHead")
	proto.RegisterType((*Contract)(nil), "protos.Contract")
}

func init() { proto.RegisterFile("contract.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xcd, 0x6e, 0x23, 0x45,
	0x10, 0x96, 0xed, 0xd8, 0xb1, 0xcb, 0x3f, 0xc9, 0xf6, 0x3a, 0xab, 0x61, 0xb5, 0x44, 0xd6, 0x68,
	0x41, 0x16, 0x12, 0x11, 0x04, 0x0e, 0xd1, 0x0a, 0x04, 0x8e, 0x9d, 0x55, 0x82, 0x36, 0xbb, 0xd1,
	0x38, 0xe4, 0xde, 0xf1, 0x34, 0x66, 0xb4, 0x71, 0x8f, 0xd5, 0xdd, 0xb3, 0xd8, 0x37, 0xce, 0x1c,
	0x78, 0x14, 0x4e, 0xbc, 0x00, 0x77, 0x2e, 0xbc, 0x11, 0xaa, 0x9a, 0x9e, 0x5f, 0x7b, 0x43, 0x24,
	0xa4, 0x3d, 0x79, 0xea, 0xab, 0xbf, 0xae, 0xea, 0xaa, 0xea, 0x32, 0xf4, 0x66, 0xa1, 0x34, 0x8a,
	0xcf, 0xcc, 0xd1, 0x52, 0x85, 0x26, 0x64, 0x0d, 0xfa, 0xd1, 0xee, 0x1a, 0x1e, 0x8d, 0x2d, 0x67,
	0x1a, 0xcc, 0x25, 0x37, 0x91, 0x12, 0x6c, 0x00, 0xed, 0x37, 0xbf, 0x48, 0xa1, 0xae, 0xa2, 0xdb,
	0xb7, 0x62, 0xed, 0x54, 0x06, 0x95, 0x61, 0xcb, 0xcb, 0x43, 0xec, 0x19, 0xb4, 0x52, 0x71, 0xa7,
	0x4a, 0xfc, 0x0c, 0x60, 0xcf, 0xa1, 0x8b, 0xc4, 0x75, 0xb0, 0x10, 0xda, 0xf0, 0xc5, 0xd2, 0xa9,
	0x91, 0x44, 0x11, 0x74, 0xff, 0xaa, 0x40, 0x37, 0xf1, 0x3d, 0xd2, 0x5a, 0x18, 0xe6, 0xc0, 0x2e,
	0x7d, 0x5c, 0xf8, 0xd6, 0x67, 0x42, 0x32, 0x06, 0x3b, 0xaf, 0xf9, 0x22, 0x71, 0x45, 0xdf, 0x28,
	0x3d, 0xe6, 0x4b, 0x13, 0x84, 0xd2, 0xda, 0x4f, 0x48, 0x3c, 0xff, 0x44, 0xe8, 0x99, 0x0a, 0x62,
	0xee, 0x4e, 0x7c, 0xfe, 0x1c, 0x84, 0xf6, 0x7e, 0x94, 0x81, 0x71, 0xea, 0xb1, 0x3d, 0xfc, 0x66,
	0x4f, 0xa0, 0x31, 0x5a, 0x84, 0x91, 0x34, 0x4e, 0x63, 0x50, 0x19, 0x56, 0x3d, 0x4b, 0xb1, 0xa7,
	0xd0, 0xbc, 0x14, 0x86, 0x4f, 0xb8, 0xe1, 0xce, 0xee, 0xa0, 0x32, 0xec, 0x78, 0x29, 0xed, 0x9e,
	0xc2, 0xfe, 0xd9, 0x6a, 0xa9, 0x84, 0xd6, 0x41, 0x28, 0x3d, 0xa1, 0xa3, 0x3b, 0x2b, 0xaf, 0xb5,
	0xe6, 0x73, 0x61, 0xc3, 0x48, 0x69, 0xf4, 0x3b, 0x0e, 0xfd, 0x34, 0x0e, 0xfc, 0x76, 0x7f, 0xab,
	0x42, 0x7f, 0x1c, 0x2e, 0x96, 0xa1, 0x14, 0xd2, 0xe8, 0xcc, 0x1c, 0xeb, 0x43, 0x7d, 0x2c, 0x31,
	0xea, 0xd8, 0x4a, 0x4c, 0x10, 0x6a, 0xd6, 0xcb, 0xc4, 0x46, 0x4c, 0xfc, 0xaf, 0x64, 0x3c, 0x87,
	0x6e, 0xe6, 0x75, 0x6a, 0x94, 0xcd, 0x4a, 0x11, 0x64, 0x93, 0xcd, 0x50, 0x29, 0x51, 0xed, 0x63,
	0x27, 0xae, 0x29, 0x7d, 0x54, 0xe6, 0x7b, 0x9b, 0xc9, 0x39, 0x04, 0x78, 0x15, 0xce, 0x83, 0xd9,
	0x0d, 0xbf, 0x8b, 0x04, 0xa5, 0xb3, 0xe5, 0xe5, 0x10, 0xf7, 0x8f, 0x1a, 0x16, 0x85, 0x4d, 0x06,
	0xa6, 0xf8, 0x83, 0x65, 0xe1, 0x10, 0xe0, 0x32, 0xf4, 0x83, 0x9f, 0xd6, 0x13, 0x6e, 0x84, 0x4d,
	0x41, 0x0e, 0x61, 0x2e, 0x74, 0xce, 0xb9, 0xf2, 0xc7, 0xa1, 0x7c, 0x77, 0x8d, 0x8e, 0x1b, 0x24,
	0x51, 0xc0, 0xd8, 0xe7, 0xd0, 0xb8, 0xe2, 0x4a, 0x48, 0xe3, 0x34, 0x29, 0x33, 0x07, 0x49, 0x66,
	0x0a, 0x21, 0x79, 0x56, 0x08, 0xbb, 0xe8, 0x92, 0x4b, 0x9f, 0x9b, 0x50, 0xad, 0x9d, 0xd6, 0xa0,
	0x32, 0x6c, 0x7a, 0x19, 0x90, 0xd6, 0x68, 0x3b, 0x57, 0xa3, 0xdf, 0xc0, 0xee, 0x1b, 0x3a, 0xae,
	0x76, 0xba, 0x83, 0xda, 0xb0, 0x7d, 0xec, 0x6e, 0xf5, 0x70, 0x64, 0x85, 0xce, 0xa4, 0x51, 0x6b,
	0x2f, 0x51, 0xc1, 0x0a, 0x7f, 0x19, 0xaa, 0x05, 0x37, 0xce, 0x1e, 0xd9, 0xb4, 0xd4, 0xd3, 0x17,
	0xd0, 0xc9, 0x2b, 0xb0, 0x7d, 0xa8, 0x65, 0x7d, 0x8f, 0x9f, 0x98, 0xee, 0x77, 0x74, 0x63, 0x98,
	0xee, 0xba, 0x17, 0x13, 0x2f, 0xaa, 0x27, 0x15, 0xf7, 0xd7, 0x0a, 0x3c, 0x99, 0x8a, 0x3b, 0x31,
	0x33, 0xa7, 0x8a, 0xcb, 0xd9, 0xcf, 0xb9, 0xfa, 0xfd, 0x02, 0x1e, 0x97, 0x31, 0xac, 0xae, 0xd8,
	0xec, 0x36, 0x16, 0xfb, 0x1a, 0x0e, 0xca, 0xf0, 0x4d, 0xea, 0xb6, 0xe5, 0x6d, 0x67, 0xba, 0x7f,
	0xef, 0x66, 0x43, 0x2c, 0x4d, 0xc3, 0x07, 0xab, 0x9b, 0x3e, 0xd4, 0xa7, 0x26, 0x2b, 0x99, 0x98,
	0x60, 0xdf, 0x43, 0xe7, 0x4a, 0x89, 0x71, 0x28, 0xfd, 0x80, 0x14, 0x1b, 0x74, 0x5b, 0xcf, 0x36,
	0x6e, 0x2b, 0xd7, 0xef, 0x5e, 0x41, 0x83, 0xfd, 0x80, 0x41, 0x2d, 0x96, 0x77, 0xc2, 0xe4, 0xcc,
	0xec, 0x3e, 0xc0, 0xcc, 0xa6, 0x1a, 0x3b, 0x87, 0xfd, 0x49, 0xa0, 0x67, 0x71, 0xa9, 0x5a, 0x53,
	0xcd, 0x07, 0x98, 0xda, 0xd0, 0xc2, 0x92, 0x7d, 0x2d, 0x56, 0xe6, 0x9a, 0xeb, 0xb7, 0xda, 0x69,
	0x0d, 0x6a, 0x38, 0xf8, 0x53, 0x80, 0x7d, 0x09, 0x4d, 0x2c, 0xbf, 0x57, 0x81, 0x36, 0x0e, 0x90,
	0xfd, 0xf7, 0x74, 0x40, 0x2a, 0xc6, 0x6e, 0xe1, 0x63, 0xfc, 0xa6, 0x9b, 0x9c, 0x0a, 0x63, 0x84,
	0xca, 0xfc, 0x93, 0x9d, 0xf6, 0x03, 0xce, 0x79, 0xbf, 0x09, 0xf6, 0x1d, 0x74, 0xc7, 0x5c, 0xfa,
	0x81, 0xcf, 0x8d, 0x20, 0x9b, 0x1d, 0xea, 0xce, 0x8f, 0x32, 0x9b, 0xa5, 0xe2, 0xf1, 0x8a, 0xf2,
	0x6c, 0x04, 0xbd, 0x89, 0x98, 0x05, 0xb9, 0xc9, 0xd7, 0xfd, 0x2f, 0x0b, 0x25, 0x05, 0x7c, 0x15,
	0x30, 0x47, 0xe4, 0xbe, 0x47, 0x79, 0x4b, 0x69, 0xf6, 0x19, 0xec, 0x4f, 0xa3, 0xe5, 0x32, 0x54,
	0x66, 0xa4, 0xe6, 0xd1, 0x02, 0x83, 0x73, 0xf6, 0x48, 0x66, 0x03, 0x47, 0xd9, 0xd1, 0x9c, 0x07,
	0x52, 0xe7, 0x64, 0xf7, 0x63, 0xd9, 0x32, 0x8e, 0x65, 0x6d, 0xf5, 0x9d, 0x47, 0xd4, 0xb7, 0x09,
	0x89, 0xb3, 0xe5, 0x5a, 0xac, 0x8c, 0xc3, 0x48, 0x93, 0xbe, 0xd9, 0xa7, 0xd0, 0xc3, 0x13, 0x9d,
	0xad, 0xc4, 0x2c, 0x32, 0xe2, 0xc2, 0x5f, 0x39, 0x8f, 0x49, 0xa9, 0x84, 0xe2, 0x14, 0x41, 0xe4,
	0xc2, 0x77, 0xfa, 0xf1, 0x14, 0x89, 0x29, 0xf6, 0x12, 0x7a, 0xf9, 0x41, 0x20, 0xb4, 0x73, 0x40,
	0x57, 0x77, 0x98, 0x24, 0x69, 0xfb, 0x98, 0xf0, 0x4a, 0x5a, 0xee, 0x3f, 0x3b, 0xd0, 0x49, 0xf2,
	0x79, 0x1a, 0xfa, 0x6b, 0x9c, 0xcc, 0x09, 0x9d, 0x6e, 0x06, 0x39, 0x24, 0xeb, 0xf4, 0xea, 0xd6,
	0x4e, 0xaf, 0xbd, 0xa7, 0xd3, 0x77, 0xee, 0xed, 0xf4, 0xfa, 0xd6, 0x77, 0x32, 0xdd, 0x95, 0xa8,
	0xe3, 0xe3, 0x27, 0xa0, 0x08, 0x92, 0x07, 0x25, 0x70, 0x84, 0xdb, 0xe7, 0x2d, 0x21, 0x29, 0x0e,
	0xfc, 0x14, 0xb8, 0x03, 0xd1, 0x0b, 0x81, 0x71, 0xa4, 0x08, 0x2d, 0x55, 0x86, 0x2b, 0x43, 0xec,
	0x96, 0x5d, 0xaa, 0x12, 0x00, 0xed, 0x9e, 0x49, 0x9f, 0x78, 0x10, 0xdb, 0xb5, 0x24, 0x5e, 0x5c,
	0x72, 0x04, 0xda, 0xd1, 0x34, 0xf5, 0x4c, 0xcb, 0x2b, 0xa1, 0xec, 0xdb, 0x4c, 0x8e, 0xf6, 0x2a,
	0xed, 0x74, 0xca, 0x3d, 0x9a, 0xe3, 0x7a, 0x25, 0x61, 0x76, 0x01, 0x6c, 0x63, 0x55, 0x4c, 0x9e,
	0xa1, 0x8d, 0x46, 0x48, 0x25, 0xbc, 0x2d, 0x4a, 0x79, 0x53, 0x59, 0x3f, 0x53, 0x5b, 0xdc, 0xdb,
	0x53, 0x5b, 0x94, 0xf0, 0x52, 0x70, 0x1b, 0x1b, 0x19, 0xa3, 0x82, 0xdb, 0xc8, 0x08, 0x7a, 0xda,
	0x3a, 0x5e, 0x11, 0x74, 0xff, 0xac, 0x64, 0x35, 0x75, 0x2e, 0xb8, 0x4f, 0xaf, 0x3d, 0x0f, 0x64,
	0x61, 0xc3, 0xcd, 0x21, 0x98, 0xed, 0x1b, 0xa1, 0xb0, 0x3e, 0xed, 0x93, 0x97, 0x90, 0xa8, 0x39,
	0xd2, 0xda, 0x6e, 0xb2, 0xb6, 0xb8, 0x72, 0x08, 0x2d, 0xcf, 0x4b, 0xa1, 0x92, 0x6b, 0xb6, 0x2f,
	0x46, 0x0e, 0x62, 0x43, 0xd8, 0x1b, 0x87, 0x52, 0x0b, 0xa9, 0x23, 0x6d, 0xc7, 0x49, 0x9d, 0x7c,
	0x94, 0x61, 0xf7, 0xf7, 0x0a, 0x34, 0x93, 0x63, 0xb3, 0x1e, 0x54, 0x83, 0xa4, 0xfc, 0xab, 0x81,
	0xcf, 0x4e, 0x8a, 0x21, 0xd1, 0x39, 0xdb, 0xc7, 0xfd, 0x72, 0xfa, 0x90, 0xe7, 0x15, 0x83, 0x3f,
	0x29, 0x36, 0x18, 0x05, 0xb1, 0x45, 0x13, 0x79, 0x5e, 0x41, 0xf2, 0xf4, 0x13, 0xe8, 0xcf, 0xc2,
	0xc5, 0x51, 0x24, 0x83, 0x3b, 0xe1, 0xcf, 0x85, 0xb2, 0x2a, 0xa7, 0xdd, 0x2b, 0xfc, 0x4d, 0x44,
	0x6f, 0xe3, 0x7f, 0x17, 0x5f, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x07, 0xbc, 0x95, 0x20, 0x76,
	0x0c, 0x00, 0x00,
}
