// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contract_list.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	contract_list.proto
	contract.proto
	response_data.proto

It has these top-level messages:
	ContractList
	ContractSignature
	ContractAsset
	ExpressionResult
	ComponentsExpression
	ComponentData
	SelectBranchExpression
	ContractComponent
	ContractBody
	ContractHead
	Contract
	ResponseData
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ContractList struct {
	Contracts []*Contract `protobuf:"bytes,1,rep,name=contracts" json:"contracts"`
}

func (m *ContractList) Reset()                    { *m = ContractList{} }
func (m *ContractList) String() string            { return proto.CompactTextString(m) }
func (*ContractList) ProtoMessage()               {}
func (*ContractList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ContractList) GetContracts() []*Contract {
	if m != nil {
		return m.Contracts
	}
	return nil
}

func init() {
	proto.RegisterType((*ContractList)(nil), "protos.ContractList")
}

func init() { proto.RegisterFile("contract_list.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xce, 0xcf, 0x2b,
	0x29, 0x4a, 0x4c, 0x2e, 0x89, 0xcf, 0xc9, 0x2c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x03, 0x53, 0xc5, 0x52, 0x7c, 0x30, 0x49, 0x88, 0xb8, 0x92, 0x1d, 0x17, 0x8f, 0x33, 0x54,
	0xc4, 0x27, 0xb3, 0xb8, 0x44, 0x48, 0x8f, 0x8b, 0x13, 0xa6, 0xa2, 0x58, 0x82, 0x51, 0x81, 0x59,
	0x83, 0xdb, 0x48, 0x00, 0xa2, 0xb4, 0x58, 0x0f, 0xa6, 0x30, 0x08, 0xa1, 0xc4, 0x49, 0x93, 0x4b,
	0x24, 0x39, 0x3f, 0x57, 0xaf, 0x34, 0x2f, 0x33, 0x27, 0x35, 0x25, 0x3d, 0xb5, 0x08, 0xaa, 0xd6,
	0x49, 0x30, 0x00, 0x44, 0x23, 0x1b, 0x9d, 0x04, 0x71, 0x82, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x6c, 0x8c, 0x0f, 0xac, 0xa0, 0x00, 0x00, 0x00,
}
