// Code generated by protoc-gen-go.
// source: contract_execute_logs.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	contract_execute_logs.proto
	contract_list.proto
	contract.proto
	response_data.proto

It has these top-level messages:
	ContractExecuteLog
	ContractExecuteLogList
	ContractList
	ContractSignature
	ContractAsset
	ExpressionResult
	ComponentsExpression
	ComponentDataSub
	ComponentData
	SelectBranchExpression
	ContractComponentSub
	ContractComponent
	ContractBody
	ContractHead
	Contract
	ResponseData
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ContractExecuteLog struct {
	ContractHashId string `protobuf:"bytes,1,opt,name=ContractHashId" json:"ContractHashId"`
	// transaction.Relation.TaskId
	TaskId string `protobuf:"bytes,2,opt,name=TaskId" json:"TaskId"`
	// transaction timestamp
	Timestamp string `protobuf:"bytes,3,opt,name=Timestamp" json:"Timestamp"`
	// ContractBody.Caption
	Caption string `protobuf:"bytes,4,opt,name=Caption" json:"Caption"`
	// ContractBody.Cname
	Cname string `protobuf:"bytes,5,opt,name=Cname" json:"Cname"`
	// ContractBody.ContractId
	ContractId string `protobuf:"bytes,6,opt,name=ContractId" json:"ContractId"`
	// ContractBody.ContractOwners
	ContractOwners []string `protobuf:"bytes,7,rep,name=ContractOwners" json:"ContractOwners"`
	// ContractBody.ContractSignatures
	ContractSignatures []*ContractSignature `protobuf:"bytes,8,rep,name=ContractSignatures" json:"ContractSignatures"`
	// ContractBody.ContractState
	ContractState string `protobuf:"bytes,9,opt,name=ContractState" json:"ContractState"`
	// ContractBody.CreateTime
	CreateTime string `protobuf:"bytes,10,opt,name=CreateTime" json:"CreateTime"`
	// ContractBody.Creator
	Creator string `protobuf:"bytes,11,opt,name=Creator" json:"Creator"`
	// ContractBody.Description
	Description string `protobuf:"bytes,12,opt,name=Description" json:"Description"`
	// ContractBody.StartTime
	StartTime string `protobuf:"bytes,13,opt,name=StartTime" json:"StartTime"`
	// ContractBody.EndTime
	EndTime string `protobuf:"bytes,14,opt,name=EndTime" json:"EndTime"`
}

func (m *ContractExecuteLog) Reset()                    { *m = ContractExecuteLog{} }
func (m *ContractExecuteLog) String() string            { return proto.CompactTextString(m) }
func (*ContractExecuteLog) ProtoMessage()               {}
func (*ContractExecuteLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ContractExecuteLog) GetContractHashId() string {
	if m != nil {
		return m.ContractHashId
	}
	return ""
}

func (m *ContractExecuteLog) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *ContractExecuteLog) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *ContractExecuteLog) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *ContractExecuteLog) GetCname() string {
	if m != nil {
		return m.Cname
	}
	return ""
}

func (m *ContractExecuteLog) GetContractId() string {
	if m != nil {
		return m.ContractId
	}
	return ""
}

func (m *ContractExecuteLog) GetContractOwners() []string {
	if m != nil {
		return m.ContractOwners
	}
	return nil
}

func (m *ContractExecuteLog) GetContractSignatures() []*ContractSignature {
	if m != nil {
		return m.ContractSignatures
	}
	return nil
}

func (m *ContractExecuteLog) GetContractState() string {
	if m != nil {
		return m.ContractState
	}
	return ""
}

func (m *ContractExecuteLog) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *ContractExecuteLog) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ContractExecuteLog) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ContractExecuteLog) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *ContractExecuteLog) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type ContractExecuteLogList struct {
	ContractLogs []*ContractExecuteLog `protobuf:"bytes,1,rep,name=ContractLogs" json:"ContractLogs"`
}

func (m *ContractExecuteLogList) Reset()                    { *m = ContractExecuteLogList{} }
func (m *ContractExecuteLogList) String() string            { return proto.CompactTextString(m) }
func (*ContractExecuteLogList) ProtoMessage()               {}
func (*ContractExecuteLogList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ContractExecuteLogList) GetContractLogs() []*ContractExecuteLog {
	if m != nil {
		return m.ContractLogs
	}
	return nil
}

func init() {
	proto.RegisterType((*ContractExecuteLog)(nil), "protos.ContractExecuteLog")
	proto.RegisterType((*ContractExecuteLogList)(nil), "protos.ContractExecuteLogList")
}

func init() { proto.RegisterFile("contract_execute_logs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x4f, 0x6b, 0xc2, 0x40,
	0x10, 0xc5, 0xb1, 0xa9, 0x5a, 0xc7, 0x3f, 0x87, 0xad, 0xc8, 0xd6, 0x96, 0x12, 0xa4, 0x14, 0xa1,
	0xe0, 0xa1, 0xbd, 0xf7, 0xa0, 0x15, 0x1a, 0x10, 0x0a, 0xea, 0xa1, 0x37, 0xd9, 0x26, 0x4b, 0x1a,
	0x6a, 0x76, 0x65, 0x77, 0xa4, 0xfd, 0xd6, 0xfd, 0x0a, 0x25, 0xb3, 0x89, 0x46, 0xed, 0x29, 0xbc,
	0xdf, 0xdb, 0x99, 0xbc, 0x7d, 0x09, 0x5c, 0x87, 0x5a, 0xa1, 0x11, 0x21, 0xae, 0xe4, 0x8f, 0x0c,
	0xb7, 0x28, 0x57, 0x6b, 0x1d, 0xdb, 0xd1, 0xc6, 0x68, 0xd4, 0xac, 0x46, 0x0f, 0xdb, 0xef, 0x14,
	0x87, 0x1c, 0x1f, 0xfc, 0x7a, 0xc0, 0x26, 0x39, 0x9a, 0xba, 0xb1, 0x99, 0x8e, 0xd9, 0x3d, 0x74,
	0x0a, 0xfa, 0x2a, 0xec, 0x67, 0x10, 0xf1, 0x8a, 0x5f, 0x19, 0x36, 0xe6, 0x47, 0x94, 0xf5, 0xa0,
	0xb6, 0x14, 0xf6, 0x2b, 0x88, 0xf8, 0x19, 0xf9, 0xb9, 0x62, 0x37, 0xd0, 0x58, 0x26, 0xa9, 0xb4,
	0x28, 0xd2, 0x0d, 0xf7, 0xc8, 0xda, 0x03, 0xc6, 0xa1, 0x3e, 0x11, 0x1b, 0x4c, 0xb4, 0xe2, 0xe7,
	0xe4, 0x15, 0x92, 0x75, 0xa1, 0x3a, 0x51, 0x22, 0x95, 0xbc, 0x4a, 0xdc, 0x09, 0x76, 0x0b, 0x50,
	0xbc, 0x37, 0x88, 0x78, 0x8d, 0xac, 0x12, 0x29, 0xa7, 0x7d, 0xfb, 0x56, 0xd2, 0x58, 0x5e, 0xf7,
	0xbd, 0x72, 0x5a, 0x47, 0x59, 0xb0, 0xbf, 0xeb, 0x22, 0x89, 0x95, 0xc0, 0xad, 0x91, 0x96, 0x5f,
	0xf8, 0xde, 0xb0, 0xf9, 0x78, 0xe5, 0x0a, 0xb1, 0xa3, 0x93, 0x13, 0xf3, 0x7f, 0x86, 0xd8, 0x1d,
	0xb4, 0x77, 0x14, 0x05, 0x4a, 0xde, 0xa0, 0x54, 0x87, 0x90, 0x82, 0x1b, 0x29, 0x50, 0x66, 0x77,
	0xe7, 0x90, 0x07, 0xdf, 0x11, 0x2a, 0x22, 0x53, 0xda, 0xf0, 0x66, 0x5e, 0x84, 0x93, 0xcc, 0x87,
	0xe6, 0x8b, 0xb4, 0xa1, 0x49, 0x5c, 0x4d, 0x2d, 0x72, 0xcb, 0x28, 0xab, 0x78, 0x81, 0xc2, 0x20,
	0xad, 0x6e, 0xbb, 0x8a, 0x77, 0x20, 0xdb, 0x3c, 0x55, 0x11, 0x79, 0x1d, 0xb7, 0x39, 0x97, 0x83,
	0x77, 0xe8, 0x9d, 0x7e, 0xf0, 0x59, 0x62, 0x91, 0x3d, 0x43, 0xab, 0x70, 0x66, 0x3a, 0xb6, 0xbc,
	0x42, 0xc5, 0xf4, 0x8f, 0x8b, 0xd9, 0x4f, 0xcd, 0x0f, 0xce, 0x8f, 0x1f, 0xa0, 0x1b, 0xea, 0x74,
	0xb4, 0x55, 0xc9, 0x5a, 0x46, 0xb1, 0x34, 0xf9, 0xe0, 0xf8, 0xf2, 0x74, 0xd2, 0x7e, 0xb8, 0x1f,
	0xf2, 0xe9, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x48, 0x14, 0xc3, 0xb6, 0x02, 0x00, 0x00,
}
