// Code generated by protoc-gen-go.
// source: contract_output.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	contract_output.proto
	contract.proto
	data.proto

It has these top-level messages:
	Asset
	ConditionDetails
	Condition
	ConditionsItem
	Fulfillment
	Metadata
	RelactionSignature
	Relaction
	Transaction
	ContractOutput
	ContractAttributes
	ContractSignature
	ContractAssert
	PlanTaskCondition
	Plan
	Task
	ContractComponents
	Contract
	ContractProto
	ContractData
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// An Asset is a fungible unit to spend and lock with Transactions
type Asset struct {
	Data       *google_protobuf.Any `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Id         string               `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Divisible  bool                 `protobuf:"varint,3,opt,name=divisible" json:"divisible,omitempty"`
	Refillable bool                 `protobuf:"varint,4,opt,name=refillable" json:"refillable,omitempty"`
	Updatable  bool                 `protobuf:"varint,5,opt,name=updatable" json:"updatable,omitempty"`
}

func (m *Asset) Reset()                    { *m = Asset{} }
func (m *Asset) String() string            { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()               {}
func (*Asset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Asset) GetData() *google_protobuf.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Asset) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Asset) GetDivisible() bool {
	if m != nil {
		return m.Divisible
	}
	return false
}

func (m *Asset) GetRefillable() bool {
	if m != nil {
		return m.Refillable
	}
	return false
}

func (m *Asset) GetUpdatable() bool {
	if m != nil {
		return m.Updatable
	}
	return false
}

type ConditionDetails struct {
	Bitmask   int32  `protobuf:"varint,1,opt,name=bitmask" json:"bitmask,omitempty"`
	PublicKey string `protobuf:"bytes,2,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	Signature string `protobuf:"bytes,3,opt,name=signature" json:"signature,omitempty"`
	Type      string `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	TypeId    int32  `protobuf:"varint,5,opt,name=type_id,json=typeId" json:"type_id,omitempty"`
}

func (m *ConditionDetails) Reset()                    { *m = ConditionDetails{} }
func (m *ConditionDetails) String() string            { return proto.CompactTextString(m) }
func (*ConditionDetails) ProtoMessage()               {}
func (*ConditionDetails) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ConditionDetails) GetBitmask() int32 {
	if m != nil {
		return m.Bitmask
	}
	return 0
}

func (m *ConditionDetails) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *ConditionDetails) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *ConditionDetails) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ConditionDetails) GetTypeId() int32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

type Condition struct {
	Details *ConditionDetails `protobuf:"bytes,1,opt,name=details" json:"details,omitempty"`
	Uri     string            `protobuf:"bytes,2,opt,name=uri" json:"uri,omitempty"`
}

func (m *Condition) Reset()                    { *m = Condition{} }
func (m *Condition) String() string            { return proto.CompactTextString(m) }
func (*Condition) ProtoMessage()               {}
func (*Condition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Condition) GetDetails() *ConditionDetails {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *Condition) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

type ConditionsItem struct {
	Amount      int64      `protobuf:"varint,1,opt,name=amount" json:"amount,omitempty"`
	Cid         int32      `protobuf:"varint,2,opt,name=cid" json:"cid,omitempty"`
	Condition   *Condition `protobuf:"bytes,3,opt,name=condition" json:"condition,omitempty"`
	OwnersAfter []string   `protobuf:"bytes,4,rep,name=owners_after,json=ownersAfter" json:"owners_after,omitempty"`
}

func (m *ConditionsItem) Reset()                    { *m = ConditionsItem{} }
func (m *ConditionsItem) String() string            { return proto.CompactTextString(m) }
func (*ConditionsItem) ProtoMessage()               {}
func (*ConditionsItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ConditionsItem) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ConditionsItem) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *ConditionsItem) GetCondition() *Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *ConditionsItem) GetOwnersAfter() []string {
	if m != nil {
		return m.OwnersAfter
	}
	return nil
}

type Fulfillment struct {
	Fid          int32                `protobuf:"varint,1,opt,name=fid" json:"fid,omitempty"`
	OwnersBefore []string             `protobuf:"bytes,2,rep,name=owners_before,json=ownersBefore" json:"owners_before,omitempty"`
	Fulfillment  string               `protobuf:"bytes,3,opt,name=fulfillment" json:"fulfillment,omitempty"`
	Input        *google_protobuf.Any `protobuf:"bytes,4,opt,name=input" json:"input,omitempty"`
}

func (m *Fulfillment) Reset()                    { *m = Fulfillment{} }
func (m *Fulfillment) String() string            { return proto.CompactTextString(m) }
func (*Fulfillment) ProtoMessage()               {}
func (*Fulfillment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Fulfillment) GetFid() int32 {
	if m != nil {
		return m.Fid
	}
	return 0
}

func (m *Fulfillment) GetOwnersBefore() []string {
	if m != nil {
		return m.OwnersBefore
	}
	return nil
}

func (m *Fulfillment) GetFulfillment() string {
	if m != nil {
		return m.Fulfillment
	}
	return ""
}

func (m *Fulfillment) GetInput() *google_protobuf.Any {
	if m != nil {
		return m.Input
	}
	return nil
}

type Metadata struct {
	Id   string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Data *google_protobuf.Any `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (m *Metadata) Reset()                    { *m = Metadata{} }
func (m *Metadata) String() string            { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()               {}
func (*Metadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Metadata) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Metadata) GetData() *google_protobuf.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type RelactionSignature struct {
	ContractNodePubkey string `protobuf:"bytes,1,opt,name=contract_node_pubkey,json=contractNodePubkey" json:"contract_node_pubkey,omitempty"`
	Signature          string `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
}

func (m *RelactionSignature) Reset()                    { *m = RelactionSignature{} }
func (m *RelactionSignature) String() string            { return proto.CompactTextString(m) }
func (*RelactionSignature) ProtoMessage()               {}
func (*RelactionSignature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RelactionSignature) GetContractNodePubkey() string {
	if m != nil {
		return m.ContractNodePubkey
	}
	return ""
}

func (m *RelactionSignature) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

// 合约&交易关系信息
type Relaction struct {
	ContractId string                `protobuf:"bytes,1,opt,name=contract_id,json=contractId" json:"contract_id,omitempty"`
	TaskId     string                `protobuf:"bytes,2,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
	Voters     []string              `protobuf:"bytes,3,rep,name=voters" json:"voters,omitempty"`
	Signatures []*RelactionSignature `protobuf:"bytes,4,rep,name=signatures" json:"signatures,omitempty"`
}

func (m *Relaction) Reset()                    { *m = Relaction{} }
func (m *Relaction) String() string            { return proto.CompactTextString(m) }
func (*Relaction) ProtoMessage()               {}
func (*Relaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Relaction) GetContractId() string {
	if m != nil {
		return m.ContractId
	}
	return ""
}

func (m *Relaction) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *Relaction) GetVoters() []string {
	if m != nil {
		return m.Voters
	}
	return nil
}

func (m *Relaction) GetSignatures() []*RelactionSignature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

type Transaction struct {
	Asset        *Asset            `protobuf:"bytes,1,opt,name=asset" json:"asset,omitempty"`
	Conditions   []*ConditionsItem `protobuf:"bytes,2,rep,name=conditions" json:"conditions,omitempty"`
	Fulfillments []*Fulfillment    `protobuf:"bytes,3,rep,name=fulfillments" json:"fulfillments,omitempty"`
	Metadata     *Metadata         `protobuf:"bytes,4,opt,name=metadata" json:"metadata,omitempty"`
	Operation    string            `protobuf:"bytes,5,opt,name=operation" json:"operation,omitempty"`
	Timestamp    string            `protobuf:"bytes,6,opt,name=timestamp" json:"timestamp,omitempty"`
	Relaction    *Relaction        `protobuf:"bytes,7,opt,name=relaction" json:"relaction,omitempty"`
	Contracts    *ContractProto    `protobuf:"bytes,8,opt,name=contracts" json:"contracts,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Transaction) GetAsset() *Asset {
	if m != nil {
		return m.Asset
	}
	return nil
}

func (m *Transaction) GetConditions() []*ConditionsItem {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *Transaction) GetFulfillments() []*Fulfillment {
	if m != nil {
		return m.Fulfillments
	}
	return nil
}

func (m *Transaction) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Transaction) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *Transaction) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Transaction) GetRelaction() *Relaction {
	if m != nil {
		return m.Relaction
	}
	return nil
}

func (m *Transaction) GetContracts() *ContractProto {
	if m != nil {
		return m.Contracts
	}
	return nil
}

type ContractOutput struct {
	Id          string       `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Transaction *Transaction `protobuf:"bytes,2,opt,name=transaction" json:"transaction,omitempty"`
	Version     int32        `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
}

func (m *ContractOutput) Reset()                    { *m = ContractOutput{} }
func (m *ContractOutput) String() string            { return proto.CompactTextString(m) }
func (*ContractOutput) ProtoMessage()               {}
func (*ContractOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ContractOutput) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ContractOutput) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *ContractOutput) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*Asset)(nil), "protos.Asset")
	proto.RegisterType((*ConditionDetails)(nil), "protos.ConditionDetails")
	proto.RegisterType((*Condition)(nil), "protos.Condition")
	proto.RegisterType((*ConditionsItem)(nil), "protos.ConditionsItem")
	proto.RegisterType((*Fulfillment)(nil), "protos.Fulfillment")
	proto.RegisterType((*Metadata)(nil), "protos.Metadata")
	proto.RegisterType((*RelactionSignature)(nil), "protos.RelactionSignature")
	proto.RegisterType((*Relaction)(nil), "protos.Relaction")
	proto.RegisterType((*Transaction)(nil), "protos.Transaction")
	proto.RegisterType((*ContractOutput)(nil), "protos.ContractOutput")
}

func init() { proto.RegisterFile("contract_output.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 735 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0x4f, 0x6f, 0xd3, 0x4a,
	0x10, 0x97, 0x93, 0x38, 0x89, 0xc7, 0x6d, 0xd5, 0xb7, 0xaf, 0xed, 0xf3, 0xab, 0xde, 0x83, 0xe0,
	0x5e, 0x22, 0x84, 0x52, 0x94, 0x0a, 0x90, 0xb8, 0x15, 0x2a, 0xa4, 0x08, 0x01, 0x65, 0xe1, 0x1e,
	0x6d, 0xe2, 0x4d, 0xb5, 0xaa, 0xe3, 0x35, 0xde, 0x75, 0x51, 0xbe, 0x04, 0x07, 0x0e, 0x48, 0x1c,
	0xf8, 0x94, 0x7c, 0x01, 0xb4, 0x7f, 0xed, 0x36, 0x42, 0x9c, 0xb2, 0x33, 0xf3, 0x9b, 0xd9, 0xf1,
	0xfc, 0x7e, 0xb3, 0x81, 0xc3, 0x25, 0x2f, 0x64, 0x45, 0x96, 0x72, 0xce, 0x6b, 0x59, 0xd6, 0x72,
	0x52, 0x56, 0x5c, 0x72, 0xd4, 0xd7, 0x3f, 0xe2, 0xf8, 0xdf, 0x2b, 0xce, 0xaf, 0x72, 0x7a, 0xaa,
	0xcd, 0x45, 0xbd, 0x3a, 0x25, 0xc5, 0xc6, 0x40, 0x8e, 0xf7, 0x5c, 0xa6, 0xb1, 0xd3, 0x1f, 0x01,
	0x84, 0xe7, 0x42, 0x50, 0x89, 0xc6, 0xd0, 0xcb, 0x88, 0x24, 0x49, 0x30, 0x0a, 0xc6, 0xf1, 0xf4,
	0x60, 0x62, 0x6a, 0x4c, 0x5c, 0x8d, 0xc9, 0x79, 0xb1, 0xc1, 0x1a, 0x81, 0xf6, 0xa0, 0xc3, 0xb2,
	0xa4, 0x33, 0x0a, 0xc6, 0x11, 0xee, 0xb0, 0x0c, 0xfd, 0x07, 0x51, 0xc6, 0x6e, 0x98, 0x60, 0x8b,
	0x9c, 0x26, 0xdd, 0x51, 0x30, 0x1e, 0xe2, 0xc6, 0x81, 0xee, 0x01, 0x54, 0x74, 0xc5, 0xf2, 0x9c,
	0xa8, 0x70, 0x4f, 0x87, 0x5b, 0x1e, 0x95, 0x5d, 0x97, 0xaa, 0xae, 0x0a, 0x87, 0x26, 0xdb, 0x3b,
	0xd2, 0x6f, 0x01, 0xec, 0xbf, 0xe4, 0x45, 0xc6, 0x24, 0xe3, 0xc5, 0x05, 0x95, 0x84, 0xe5, 0x02,
	0x25, 0x30, 0x58, 0x30, 0xb9, 0x26, 0xe2, 0x5a, 0x77, 0x1b, 0x62, 0x67, 0xa2, 0xff, 0x01, 0xca,
	0x7a, 0x91, 0xb3, 0xe5, 0xfc, 0x9a, 0x6e, 0x6c, 0x8b, 0x91, 0xf1, 0xbc, 0xa6, 0x1b, 0x75, 0x97,
	0x60, 0x57, 0x05, 0x91, 0x75, 0x65, 0x3a, 0x8d, 0x70, 0xe3, 0x40, 0x08, 0x7a, 0x72, 0x53, 0x9a,
	0x1e, 0x23, 0xac, 0xcf, 0xe8, 0x1f, 0x18, 0xa8, 0xdf, 0x39, 0xcb, 0x74, 0x6f, 0x21, 0xee, 0x2b,
	0x73, 0x96, 0xa5, 0xef, 0x21, 0xf2, 0x7d, 0xa1, 0x29, 0x0c, 0x32, 0xd3, 0x9b, 0x1d, 0x5f, 0x62,
	0xe6, 0x26, 0x26, 0x77, 0x7b, 0xc7, 0x0e, 0x88, 0xf6, 0xa1, 0x5b, 0x57, 0xcc, 0xf6, 0xa8, 0x8e,
	0xe9, 0x97, 0x00, 0xf6, 0x3c, 0x5e, 0xcc, 0x24, 0x5d, 0xa3, 0x23, 0xe8, 0x93, 0x35, 0xaf, 0x0b,
	0xa9, 0xeb, 0x76, 0xb1, 0xb5, 0x54, 0xf2, 0xd2, 0x72, 0x10, 0x62, 0x75, 0x44, 0xa7, 0x10, 0x2d,
	0x5d, 0xae, 0xfe, 0xb4, 0x78, 0xfa, 0xd7, 0x56, 0x13, 0xb8, 0xc1, 0xa0, 0x07, 0xb0, 0xc3, 0x3f,
	0x17, 0xb4, 0x12, 0x73, 0xb2, 0x92, 0xb4, 0x4a, 0x7a, 0xa3, 0xee, 0x38, 0xc2, 0xb1, 0xf1, 0x9d,
	0x2b, 0x57, 0xfa, 0x35, 0x80, 0xf8, 0x55, 0x9d, 0x2b, 0xaa, 0xd6, 0xd4, 0xdc, 0xba, 0x62, 0x99,
	0x9d, 0xb9, 0x3a, 0xa2, 0x13, 0xd8, 0xb5, 0x45, 0x16, 0x74, 0xc5, 0x2b, 0x9a, 0x74, 0x74, 0x15,
	0x5b, 0xf9, 0x85, 0xf6, 0xa1, 0x11, 0xc4, 0xab, 0xa6, 0x8a, 0x9d, 0x7b, 0xdb, 0x85, 0x1e, 0x42,
	0xc8, 0x8a, 0xb2, 0x96, 0x7a, 0xf4, 0xbf, 0x13, 0x9f, 0x81, 0xa4, 0x17, 0x30, 0x7c, 0x43, 0x25,
	0x69, 0x29, 0x31, 0xf0, 0x4a, 0x74, 0x1a, 0xee, 0xfc, 0x49, 0xc3, 0x69, 0x06, 0x08, 0xd3, 0x9c,
	0x2c, 0xd5, 0x28, 0x3e, 0x78, 0x05, 0x3c, 0x86, 0x03, 0xbf, 0x59, 0x05, 0xcf, 0xe8, 0xbc, 0xac,
	0x17, 0x4a, 0x48, 0xe6, 0x06, 0xe4, 0x62, 0x6f, 0x79, 0x46, 0x2f, 0x75, 0xe4, 0xb6, 0xa2, 0x3a,
	0x77, 0x14, 0x95, 0x7e, 0x0f, 0x20, 0xf2, 0xd7, 0xa0, 0xfb, 0x10, 0xfb, 0xea, 0xbe, 0x6d, 0x70,
	0xae, 0x59, 0xa6, 0xc5, 0x46, 0xc4, 0xf5, 0xdc, 0x6f, 0x57, 0x5f, 0x99, 0xb3, 0x4c, 0xc9, 0xe0,
	0x86, 0x4b, 0x5a, 0x89, 0xa4, 0xab, 0xe7, 0x6b, 0x2d, 0xf4, 0x1c, 0xc0, 0x5f, 0x26, 0x34, 0x83,
	0xf1, 0xf4, 0xd8, 0xb1, 0xbe, 0xfd, 0x7d, 0xb8, 0x85, 0x4e, 0x7f, 0x76, 0x20, 0xfe, 0x58, 0x91,
	0x42, 0xd8, 0xee, 0x4e, 0x20, 0x24, 0xea, 0x21, 0xb0, 0x0a, 0xde, 0x75, 0x65, 0xf4, 0xeb, 0x80,
	0x4d, 0x0c, 0x3d, 0x05, 0xf0, 0x0a, 0x12, 0x9a, 0xec, 0x78, 0x7a, 0xb4, 0x25, 0x33, 0xad, 0x5d,
	0xdc, 0x42, 0xa2, 0x67, 0xb0, 0xd3, 0xe2, 0xdb, 0x7c, 0x46, 0x3c, 0xfd, 0xdb, 0x65, 0xb6, 0x44,
	0x86, 0x6f, 0x01, 0xd1, 0x23, 0x18, 0xae, 0x2d, 0xdb, 0x56, 0x1c, 0xfb, 0x2e, 0xc9, 0xa9, 0x00,
	0x7b, 0x84, 0x62, 0x83, 0x97, 0xb4, 0x22, 0x7a, 0x09, 0x42, 0xc3, 0x86, 0x77, 0xa8, 0xa8, 0x64,
	0x6b, 0x2a, 0x24, 0x59, 0x97, 0x49, 0xdf, 0x44, 0xbd, 0x43, 0x2d, 0x50, 0xe5, 0x26, 0x96, 0x0c,
	0x6e, 0x2f, 0x90, 0x1f, 0x25, 0x6e, 0x30, 0xe8, 0x4c, 0x6f, 0x9c, 0xe6, 0x4e, 0x24, 0x43, 0x9d,
	0x70, 0xd8, 0x1a, 0x85, 0x0e, 0x5c, 0x2a, 0x13, 0x37, 0xb8, 0xf4, 0x93, 0x5e, 0x71, 0x6d, 0xbc,
	0xd3, 0x4f, 0xf7, 0x96, 0x86, 0x9f, 0x40, 0x2c, 0x1b, 0x5a, 0xac, 0x94, 0xfd, 0xa4, 0x5a, 0x8c,
	0xe1, 0x36, 0x4e, 0xbd, 0x89, 0x37, 0xb4, 0x12, 0x6e, 0xfb, 0x43, 0xec, 0xcc, 0x85, 0xf9, 0x57,
	0x38, 0xfb, 0x15, 0x00, 0x00, 0xff, 0xff, 0x23, 0x01, 0x53, 0x73, 0x35, 0x06, 0x00, 0x00,
}
