// Code generated by protoc-gen-go.
// source: contract_execute_logs.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	contract_execute_logs.proto
	contract_list.proto
	contract.proto
	response_data.proto

It has these top-level messages:
	ContractExecuteLog
	ContractExecuteLogList
	ContractList
	ContractSignature
	ContractAsset
	ExpressionResult
	ComponentsExpression
	ComponentDataSub
	ComponentData
	SelectBranchExpression
	ContractComponentSub
	ContractComponent
	ContractBody
	ContractHead
	Contract
	ResponseData
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ContractExecuteLog struct {
	ContractHashId string `protobuf:"bytes,1,opt,name=ContractHashId" json:"ContractHashId"`
	// transaction.Relation.TaskId
	TaskId string `protobuf:"bytes,2,opt,name=TaskId" json:"TaskId"`
	// transaction timestamp
	Timestamp string `protobuf:"bytes,3,opt,name=Timestamp" json:"Timestamp"`
	// ContractComponents.Caption
	Caption string `protobuf:"bytes,4,opt,name=Caption" json:"Caption"`
	// ContractComponents.Cname
	Cname string `protobuf:"bytes,5,opt,name=Cname" json:"Cname"`
	// ContractComponents.Cname
	Ctype string `protobuf:"bytes,6,opt,name=Ctype" json:"Ctype"`
	// ContractComponents.Description
	Description string `protobuf:"bytes,7,opt,name=Description" json:"Description"`
	// ContractComponents.MetaAttribute
	MetaAttribute map[string]string `protobuf:"bytes,8,rep,name=MetaAttribute" json:"MetaAttribute" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ContractComponents.State
	State string `protobuf:"bytes,9,opt,name=State" json:"State"`
	// ContractBody.CreateTime
	CreateTime string `protobuf:"bytes,10,opt,name=CreateTime" json:"CreateTime"`
}

func (m *ContractExecuteLog) Reset()                    { *m = ContractExecuteLog{} }
func (m *ContractExecuteLog) String() string            { return proto.CompactTextString(m) }
func (*ContractExecuteLog) ProtoMessage()               {}
func (*ContractExecuteLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ContractExecuteLog) GetContractHashId() string {
	if m != nil {
		return m.ContractHashId
	}
	return ""
}

func (m *ContractExecuteLog) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *ContractExecuteLog) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *ContractExecuteLog) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *ContractExecuteLog) GetCname() string {
	if m != nil {
		return m.Cname
	}
	return ""
}

func (m *ContractExecuteLog) GetCtype() string {
	if m != nil {
		return m.Ctype
	}
	return ""
}

func (m *ContractExecuteLog) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ContractExecuteLog) GetMetaAttribute() map[string]string {
	if m != nil {
		return m.MetaAttribute
	}
	return nil
}

func (m *ContractExecuteLog) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ContractExecuteLog) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

type ContractExecuteLogList struct {
	ContractLogs []*ContractExecuteLog `protobuf:"bytes,1,rep,name=ContractLogs" json:"ContractLogs"`
}

func (m *ContractExecuteLogList) Reset()                    { *m = ContractExecuteLogList{} }
func (m *ContractExecuteLogList) String() string            { return proto.CompactTextString(m) }
func (*ContractExecuteLogList) ProtoMessage()               {}
func (*ContractExecuteLogList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ContractExecuteLogList) GetContractLogs() []*ContractExecuteLog {
	if m != nil {
		return m.ContractLogs
	}
	return nil
}

func init() {
	proto.RegisterType((*ContractExecuteLog)(nil), "protos.ContractExecuteLog")
	proto.RegisterType((*ContractExecuteLogList)(nil), "protos.ContractExecuteLogList")
}

func init() { proto.RegisterFile("contract_execute_logs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x6b, 0xea, 0x40,
	0x10, 0xc6, 0x89, 0x79, 0xea, 0x73, 0x7c, 0x4f, 0x1e, 0xfb, 0x44, 0x16, 0x5b, 0x8a, 0x78, 0x28,
	0x42, 0x69, 0x0e, 0xed, 0xa5, 0xf4, 0x50, 0x5a, 0x53, 0xa1, 0x82, 0xbd, 0xa8, 0x87, 0xde, 0x64,
	0x8d, 0x43, 0x1a, 0x34, 0xd9, 0xb0, 0x3b, 0x29, 0xf5, 0x2f, 0xea, 0xbf, 0x59, 0xb2, 0x9b, 0x50,
	0x6d, 0xe8, 0x29, 0xf9, 0x7e, 0xdf, 0xcc, 0x30, 0xdf, 0xb0, 0x70, 0x12, 0xc8, 0x84, 0x94, 0x08,
	0x68, 0x85, 0xef, 0x18, 0x64, 0x84, 0xab, 0x9d, 0x0c, 0xb5, 0x97, 0x2a, 0x49, 0x92, 0x35, 0xcc,
	0x47, 0xf7, 0x3b, 0x65, 0x91, 0xe5, 0xc3, 0x0f, 0x17, 0x98, 0x5f, 0xa0, 0x89, 0x6d, 0x9b, 0xc9,
	0x90, 0x9d, 0x43, 0xa7, 0xa4, 0x4f, 0x42, 0xbf, 0x4e, 0x37, 0xdc, 0x19, 0x38, 0xa3, 0xd6, 0xfc,
	0x1b, 0x65, 0x3d, 0x68, 0x2c, 0x85, 0xde, 0x4e, 0x37, 0xbc, 0x66, 0xfc, 0x42, 0xb1, 0x53, 0x68,
	0x2d, 0xa3, 0x18, 0x35, 0x89, 0x38, 0xe5, 0xae, 0xb1, 0xbe, 0x00, 0xe3, 0xd0, 0xf4, 0x45, 0x4a,
	0x91, 0x4c, 0xf8, 0x2f, 0xe3, 0x95, 0x92, 0x75, 0xa1, 0xee, 0x27, 0x22, 0x46, 0x5e, 0x37, 0xdc,
	0x0a, 0x43, 0x69, 0x9f, 0x22, 0x6f, 0x14, 0x34, 0x17, 0x6c, 0x00, 0xed, 0x47, 0xd4, 0x81, 0x8a,
	0xec, 0xa4, 0xa6, 0xf1, 0x0e, 0x11, 0x5b, 0xc0, 0xdf, 0x67, 0x24, 0xf1, 0x40, 0xa4, 0xa2, 0x75,
	0x46, 0xc8, 0x7f, 0x0f, 0xdc, 0x51, 0xfb, 0xea, 0xd2, 0x66, 0xd7, 0x5e, 0x35, 0xb8, 0x77, 0x54,
	0x3f, 0x49, 0x48, 0xed, 0xe7, 0xc7, 0x33, 0xf2, 0x65, 0x16, 0x24, 0x08, 0x79, 0xcb, 0x2e, 0x63,
	0x04, 0x3b, 0x03, 0xf0, 0x15, 0x0a, 0xc2, 0x3c, 0x25, 0x07, 0x63, 0x1d, 0x90, 0xfe, 0x3d, 0xb0,
	0xea, 0x68, 0xf6, 0x0f, 0xdc, 0x2d, 0xee, 0x8b, 0xdb, 0xe6, 0xbf, 0xf9, 0xf4, 0x37, 0xb1, 0xcb,
	0xb0, 0xb8, 0xa7, 0x15, 0xb7, 0xb5, 0x1b, 0x67, 0xf8, 0x02, 0xbd, 0xea, 0xbe, 0xb3, 0x48, 0x13,
	0xbb, 0x83, 0x3f, 0xa5, 0x33, 0x93, 0xa1, 0xe6, 0x8e, 0x49, 0xd9, 0xff, 0x39, 0xe5, 0xfc, 0xa8,
	0x7e, 0x7c, 0x01, 0xdd, 0x40, 0xc6, 0x5e, 0x96, 0x44, 0x3b, 0xdc, 0x84, 0xa8, 0x8a, 0xc6, 0xf1,
	0xff, 0x6a, 0xa7, 0x5e, 0xdb, 0x87, 0x74, 0xfd, 0x19, 0x00, 0x00, 0xff, 0xff, 0x42, 0x24, 0xd2,
	0x79, 0x6e, 0x02, 0x00, 0x00,
}
