// Code generated by protoc-gen-go. DO NOT EDIT.
// source: response_contract.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ResponseContract struct {
	// response code, 9bit
	Code int32 `protobuf:"varint,1,opt,name=code" json:"code"`
	// response message
	Msg string `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	// response data
	Result *Contract `protobuf:"bytes,3,opt,name=result" json:"result"`
}

func (m *ResponseContract) Reset()                    { *m = ResponseContract{} }
func (m *ResponseContract) String() string            { return proto.CompactTextString(m) }
func (*ResponseContract) ProtoMessage()               {}
func (*ResponseContract) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *ResponseContract) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseContract) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResponseContract) GetResult() *Contract {
	if m != nil {
		return m.Result
	}
	return nil
}

type ResponsePaginationContract struct {
	// response code, 9bit
	Code int32 `protobuf:"varint,1,opt,name=code" json:"code"`
	// response message
	Msg string `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	// response data
	Result *PaginationContract `protobuf:"bytes,3,opt,name=result" json:"result"`
}

func (m *ResponsePaginationContract) Reset()                    { *m = ResponsePaginationContract{} }
func (m *ResponsePaginationContract) String() string            { return proto.CompactTextString(m) }
func (*ResponsePaginationContract) ProtoMessage()               {}
func (*ResponsePaginationContract) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *ResponsePaginationContract) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponsePaginationContract) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResponsePaginationContract) GetResult() *PaginationContract {
	if m != nil {
		return m.Result
	}
	return nil
}

type PaginationContract struct {
	// current_pageNum
	Page int32 `protobuf:"varint,1,opt,name=page" json:"page"`
	// page_size
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize" json:"page_size"`
	// total page number
	Total int32 `protobuf:"varint,3,opt,name=total" json:"total"`
	// pagination data for contractList
	Data []*Contract `protobuf:"bytes,4,rep,name=data" json:"data"`
}

func (m *PaginationContract) Reset()                    { *m = PaginationContract{} }
func (m *PaginationContract) String() string            { return proto.CompactTextString(m) }
func (*PaginationContract) ProtoMessage()               {}
func (*PaginationContract) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *PaginationContract) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PaginationContract) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PaginationContract) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PaginationContract) GetData() []*Contract {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ResponseContract)(nil), "protos.ResponseContract")
	proto.RegisterType((*ResponsePaginationContract)(nil), "protos.ResponsePaginationContract")
	proto.RegisterType((*PaginationContract)(nil), "protos.PaginationContract")
}

func init() { proto.RegisterFile("response_contract.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x31, 0x6b, 0xc3, 0x30,
	0x10, 0x85, 0x51, 0x6d, 0x87, 0xe6, 0x0a, 0xc5, 0x1c, 0x81, 0x1a, 0x77, 0xa8, 0x09, 0x1d, 0x3c,
	0x79, 0x48, 0x87, 0xee, 0xe9, 0x1f, 0x08, 0xea, 0x0f, 0x08, 0x8a, 0x2d, 0x8c, 0xc0, 0x91, 0x8c,
	0x74, 0xe9, 0x90, 0xad, 0xff, 0xbc, 0x48, 0x96, 0x03, 0x6d, 0xd3, 0xa1, 0xd3, 0x7b, 0xba, 0x27,
	0xbd, 0x0f, 0x49, 0xf0, 0x60, 0xa5, 0x1b, 0x8d, 0x76, 0x72, 0xdf, 0x1a, 0x4d, 0x56, 0xb4, 0xd4,
	0x8c, 0xd6, 0x90, 0xc1, 0x45, 0x10, 0x57, 0xde, 0x7f, 0x9f, 0xaf, 0x0f, 0x90, 0xf3, 0x78, 0xe4,
	0x2d, 0x26, 0x88, 0x90, 0xb6, 0xa6, 0x93, 0x05, 0xab, 0x58, 0x9d, 0xf1, 0xe0, 0x31, 0x87, 0xe4,
	0xe8, 0xfa, 0xe2, 0xa6, 0x62, 0xf5, 0x92, 0x7b, 0x8b, 0x35, 0x2c, 0xac, 0x74, 0xa7, 0x81, 0x8a,
	0xa4, 0x62, 0xf5, 0xdd, 0x26, 0x9f, 0x1a, 0x5d, 0x33, 0xf7, 0xf0, 0x98, 0xaf, 0x3f, 0xa0, 0x9c,
	0x19, 0x3b, 0xd1, 0x2b, 0x2d, 0x48, 0x19, 0xfd, 0x4f, 0xda, 0xe6, 0x07, 0xad, 0x9c, 0x69, 0xbf,
	0x1b, 0x2f, 0xdc, 0x4f, 0x06, 0x78, 0x1d, 0x38, 0x8a, 0xfe, 0x02, 0xf4, 0x1e, 0x1f, 0x61, 0xe9,
	0x75, 0xef, 0xd4, 0x59, 0x06, 0x6c, 0xc6, 0x6f, 0xfd, 0xe0, 0x5d, 0x9d, 0x25, 0xae, 0x20, 0x23,
	0x43, 0x62, 0x08, 0xe8, 0x8c, 0x4f, 0x0b, 0x7c, 0x86, 0xb4, 0x13, 0x24, 0x8a, 0xb4, 0x4a, 0xae,
	0xde, 0x3e, 0xa4, 0xdb, 0x57, 0x58, 0xb5, 0xe6, 0xd8, 0x9c, 0xb4, 0x1a, 0x64, 0xd7, 0x4b, 0x1b,
	0xb7, 0x6d, 0x9f, 0x76, 0x5e, 0xff, 0x7e, 0x96, 0xc3, 0xf4, 0x61, 0x2f, 0x5f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x7c, 0x32, 0x9e, 0x8f, 0xd2, 0x01, 0x00, 0x00,
}
