// Code generated by protoc-gen-go. DO NOT EDIT.
// source: response_contract_execute_logs.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ResponseContractExecuteLog struct {
	// response code, 9bit
	Code int32 `protobuf:"varint,1,opt,name=code" json:"code"`
	// response message
	Msg string `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	// response data
	Result *ContractExecuteLog `protobuf:"bytes,3,opt,name=result" json:"result"`
}

func (m *ResponseContractExecuteLog) Reset()                    { *m = ResponseContractExecuteLog{} }
func (m *ResponseContractExecuteLog) String() string            { return proto.CompactTextString(m) }
func (*ResponseContractExecuteLog) ProtoMessage()               {}
func (*ResponseContractExecuteLog) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *ResponseContractExecuteLog) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseContractExecuteLog) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResponseContractExecuteLog) GetResult() *ContractExecuteLog {
	if m != nil {
		return m.Result
	}
	return nil
}

type ResponsePaginationContractExecuteLog struct {
	// response code, 9bit
	Code int32 `protobuf:"varint,1,opt,name=code" json:"code"`
	// response message
	Msg string `protobuf:"bytes,2,opt,name=msg" json:"msg"`
	// response data
	Result *PaginationContractExecuteLog `protobuf:"bytes,3,opt,name=result" json:"result"`
}

func (m *ResponsePaginationContractExecuteLog) Reset()         { *m = ResponsePaginationContractExecuteLog{} }
func (m *ResponsePaginationContractExecuteLog) String() string { return proto.CompactTextString(m) }
func (*ResponsePaginationContractExecuteLog) ProtoMessage()    {}
func (*ResponsePaginationContractExecuteLog) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{1}
}

func (m *ResponsePaginationContractExecuteLog) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponsePaginationContractExecuteLog) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResponsePaginationContractExecuteLog) GetResult() *PaginationContractExecuteLog {
	if m != nil {
		return m.Result
	}
	return nil
}

type PaginationContractExecuteLog struct {
	// current_pageNum
	Page int32 `protobuf:"varint,1,opt,name=page" json:"page"`
	// page_size
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize" json:"page_size"`
	// total page number
	Total int32 `protobuf:"varint,3,opt,name=total" json:"total"`
	// pagination data for contractList
	Data []*ContractExecuteLog `protobuf:"bytes,4,rep,name=data" json:"data"`
}

func (m *PaginationContractExecuteLog) Reset()                    { *m = PaginationContractExecuteLog{} }
func (m *PaginationContractExecuteLog) String() string            { return proto.CompactTextString(m) }
func (*PaginationContractExecuteLog) ProtoMessage()               {}
func (*PaginationContractExecuteLog) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *PaginationContractExecuteLog) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PaginationContractExecuteLog) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PaginationContractExecuteLog) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PaginationContractExecuteLog) GetData() []*ContractExecuteLog {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ResponseContractExecuteLog)(nil), "protos.ResponseContractExecuteLog")
	proto.RegisterType((*ResponsePaginationContractExecuteLog)(nil), "protos.ResponsePaginationContractExecuteLog")
	proto.RegisterType((*PaginationContractExecuteLog)(nil), "protos.PaginationContractExecuteLog")
}

func init() { proto.RegisterFile("response_contract_execute_logs.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x65, 0x92, 0x54, 0xf4, 0x58, 0x90, 0xd5, 0x21, 0x4a, 0x19, 0xa2, 0x92, 0x21, 0x53,
	0x86, 0x32, 0xc2, 0x54, 0xc4, 0xd6, 0xa1, 0x32, 0x3f, 0x20, 0x32, 0xc9, 0xc9, 0x8a, 0x94, 0xe6,
	0x22, 0xdb, 0x41, 0xa8, 0x3f, 0x81, 0x9d, 0xff, 0x8b, 0xec, 0xa4, 0x1d, 0x40, 0xb4, 0x12, 0xd3,
	0x7b, 0xb6, 0x9e, 0x9f, 0x3f, 0xdd, 0x41, 0xa6, 0xd1, 0xf4, 0xd4, 0x19, 0x2c, 0x2b, 0xea, 0xac,
	0x96, 0x95, 0x2d, 0xf1, 0x03, 0xab, 0xc1, 0x62, 0xd9, 0x92, 0x32, 0x45, 0xaf, 0xc9, 0x12, 0x9f,
	0x79, 0x31, 0xc9, 0xf2, 0x4c, 0x68, 0xf5, 0x0e, 0x89, 0x98, 0xca, 0x9e, 0xa7, 0xd8, 0xcb, 0x98,
	0xda, 0x92, 0xe2, 0x1c, 0xc2, 0x8a, 0x6a, 0x8c, 0x59, 0xca, 0xf2, 0x48, 0x78, 0xcf, 0x6f, 0x21,
	0xd8, 0x1b, 0x15, 0x5f, 0xa5, 0x2c, 0x9f, 0x0b, 0x67, 0xf9, 0x1a, 0x66, 0x1a, 0xcd, 0xd0, 0xda,
	0x38, 0x48, 0x59, 0x7e, 0xb3, 0x4e, 0xc6, 0x6e, 0x53, 0xfc, 0x6e, 0x14, 0x53, 0x72, 0xf5, 0xc9,
	0x20, 0x3b, 0x7e, 0xbc, 0x93, 0xaa, 0xe9, 0xa4, 0x6d, 0xa8, 0xfb, 0x37, 0xc2, 0xd3, 0x0f, 0x84,
	0xec, 0x88, 0x70, 0xae, 0xfb, 0x04, 0xf3, 0xc5, 0xe0, 0xee, 0x12, 0x44, 0x2f, 0xd5, 0x09, 0xc2,
	0x79, 0xbe, 0x84, 0xb9, 0xd3, 0xd2, 0x34, 0x07, 0xf4, 0x28, 0x91, 0xb8, 0x76, 0x17, 0xaf, 0xcd,
	0x01, 0xf9, 0x02, 0x22, 0x4b, 0x56, 0xb6, 0x1e, 0x27, 0x12, 0xe3, 0x81, 0x17, 0x10, 0xd6, 0xd2,
	0xca, 0x38, 0x4c, 0x83, 0x0b, 0x63, 0xf2, 0xb9, 0xcd, 0x23, 0x2c, 0x2a, 0xda, 0x17, 0x43, 0xd7,
	0xb4, 0x58, 0x2b, 0xd4, 0xd3, 0x83, 0xcd, 0xfd, 0xce, 0xe9, 0xdf, 0xe3, 0xdb, 0x92, 0x32, 0x6f,
	0xe3, 0xfa, 0x1f, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x43, 0xe4, 0xa1, 0x60, 0x2d, 0x02, 0x00,
	0x00,
}
